### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by IndieCoderMM** [Trast00/Minimalist-todo#5]
# Highlights
- Clean and organized code
- Good use of ES6 syntax
- All features work perfectly

# Suggestions
- It would be better to use `<header>` instead of `<div>` since it makes HTML more semantic. ([index.html](https://github.com/Trast00/Minimalist-todo/blob/main/src/index.html#L14-L16))
- It would be better to add `max-height` to the tasks container to display all the contents properly when there are many tasks.
- It would be better to validate the input value before adding tasks to the list.

**Comment by Lookingfor00** [comment]
Hi @IndieCoderMM, thank you for these great suggestions. 🤝 👍  

The suggestions have been applied in this [pull request 8](https://github.com/Trast00/Minimalist-todo/pull/8#issue-1524514877)

_Feel free to leave any questions or comments if something is not 100% clear.
Please ping me [@Trast00](https://github.com/trast00) when you comment so I can receive the notification or use slack with the same name._
